name: Release Build

on:
  # Déclenchement sur push d'un tag correspondant à "v*.*.*"
  push:
    tags: [ "v*.*.*" ]
  # Déclenchement sur création d'une release
  release:
    types: [created]

jobs:
  build-jar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle

      # Construction avec Gradle (sans tests)
      - name: Build with Gradle
        run: ./gradlew clean build -x test

      # Publication dans GitHub Packages (Maven) seulement si on est sur un tag (push)
      - name: Publish to GitHub Packages
        if: github.ref_type == 'tag' && startsWith(github.ref, 'refs/tags/v')
        run: ./gradlew publish
        env:
          USERNAME: ${{ github.actor }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # On récupère le vrai nom du .jar (uniquement si c’est une release)
      - name: Find built jar name
        id: find_jar
        if: ${{ github.event_name == 'release' }}
        shell: bash
        run: echo "jar_name=$(basename $(ls build/libs/wylog-*.jar))" >> $GITHUB_OUTPUT

      # Upload du .jar sur la release GitHub (uniquement si c’est une release)
      - name: Upload JAR to release
        if: ${{ github.event_name == 'release' }}
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: build/libs/${{ steps.find_jar.outputs.jar_name }}
          asset_name: ${{ steps.find_jar.outputs.jar_name }}
          asset_content_type: application/java-archive
